# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 000-S3-AD

stages:
- stage: PythonConfig
  jobs:
  - job: PythonConfigJob
    steps:
    - template: /templates/template-python.yml

- stage: runAWS
  jobs:
  - job: runAWSJob
    steps:
    - template: /templates/template-aws-cli.yml